const cfg=window.RB_CONFIG||{};const key="redbank-rsvps-v1";let selected=new Date();selected.setHours(0,0,0,0);let editing=null;
const pad=n=>String(n).padStart(2,"0"), iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;const dateText=d=>d.toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"});
const times=["3:00 PM","4:00 PM","5:00 PM","5:30 PM","6:00 PM","6:30 PM","7:00 PM","7:30 PM","8:00 PM","8:30 PM","9:00 PM"];const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random();
function clean(){const today=iso(new Date());let all=JSON.parse(localStorage.getItem(key)||"[]").filter(x=>x.date>=today);localStorage.setItem(key,JSON.stringify(all));return all}function localGet(){return clean().filter(x=>x.date===iso(selected)).sort((a,b)=>a.arrive.localeCompare(b.arrive))}
async function get(){if(cfg.supabaseUrl&&cfg.supabaseAnonKey){const r=await fetch(`${cfg.supabaseUrl}/rest/v1/rsvps?date=eq.${iso(selected)}&order=arrive.asc`,{headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`}});return r.ok?await r.json():[]}return localGet()}
async function save(x){if(cfg.supabaseUrl&&cfg.supabaseAnonKey){const r=await fetch(`${cfg.supabaseUrl}/rest/v1/rsvps`,{method:"POST",headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(x)});if(!r.ok)throw Error("Could not save")}else{const a=clean();a.push(x);localStorage.setItem(key,JSON.stringify(a))}}
async function remove(x){if(cfg.supabaseUrl&&cfg.supabaseAnonKey){await fetch(`${cfg.supabaseUrl}/rest/v1/rsvps?id=eq.${x.id}&edit_code=eq.${x.edit_code}`,{method:"DELETE",headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`}})}else{localStorage.setItem(key,JSON.stringify(clean().filter(y=>y.id!==x.id)))}}
function renderTabs(){const el=document.querySelector("#day-tabs");el.innerHTML="";for(let i=0;i<7;i++){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+i);const b=document.createElement("button");b.className="day"+(iso(d)===iso(selected)?" active":"")+(i===0?" today":"");b.innerHTML=`<strong>${i===0?"TODAY":d.toLocaleDateString(undefined,{weekday:"short"}).toUpperCase()}</strong><span>${d.getDate()}</span>`;b.onclick=()=>{selected=d;render()};el.appendChild(b)}}
async function render(){renderTabs();document.querySelector("#selected-date").textContent=dateText(selected);const list=await get();document.querySelector("#player-count").textContent=list.length;const el=document.querySelector("#players");el.innerHTML=`<h2>Players for ${selected.toLocaleDateString(undefined,{weekday:"long"})}</h2>`+(list.length?list.map(x=>`<article class="player"><div><div class="player-name">${esc(x.nickname)} <span class="badge">${esc(x.level)}</span></div><div class="player-meta">${esc(x.arrive)}–${esc(x.leave)} · ${esc(x.game)}</div></div><div class="status">${esc(x.status)}</div></article>`).join(""):"<div class=\"empty\">No RSVPs yet. Be the first to let players know you’re coming!</div>")}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function toast(s){const t=document.querySelector("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),4500)}
function openForm(){document.querySelector("#form-card").classList.remove("hidden");document.querySelector("#show-form").classList.add("hidden");document.querySelector("[name=nickname]").focus()}function closeForm(){document.querySelector("#form-card").classList.add("hidden");document.querySelector("#show-form").classList.remove("hidden");document.querySelector("#rsvp-form").reset()}
document.querySelector("[name=arrive]").innerHTML=times.map(t=>`<option>${t}</option>`).join("");document.querySelector("[name=leave]").innerHTML=times.slice(1).map(t=>`<option>${t}</option>`).join("");document.querySelector("#show-form").onclick=openForm;document.querySelector("#close-form").onclick=closeForm;
document.querySelector("#rsvp-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const x={id:id(),date:iso(selected),nickname:f.get("nickname").trim(),level:f.get("level"),arrive:f.get("arrive"),leave:f.get("leave"),game:f.get("game"),status:f.get("status"),edit_code:Math.random().toString(36).slice(2,8).toUpperCase()};try{await save(x);closeForm();toast(`RSVP saved. Your private edit code is ${x.edit_code}`);render()}catch(err){toast("Could not save right now. Please try again.")}};render();
