const cfg=window.RB_CONFIG||{};const key="redbank-rsvps-v1";let selected=new Date();selected.setHours(0,0,0,0);let editing=null;
const pad=n=>String(n).padStart(2,"0"),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;const dateText=d=>d.toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"});
const times=["3:00 PM","4:00 PM","5:00 PM","5:30 PM","6:00 PM","6:30 PM","7:00 PM","7:30 PM","8:00 PM","8:30 PM","9:00 PM"];const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random();
function clean(){const today=iso(new Date());let all=JSON.parse(localStorage.getItem(key)||"[]").filter(x=>x.date>=today);localStorage.setItem(key,JSON.stringify(all));return all}function localGet(){return clean().filter(x=>x.date===iso(selected)).sort((a,b)=>a.arrive.localeCompare(b.arrive))}
async function get(){if(cfg.supabaseUrl&&cfg.supabaseAnonKey){const r=await fetch(`${cfg.supabaseUrl}/rest/v1/rsvps?date=eq.${iso(selected)}&order=arrive.asc`,{headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`}});return r.ok?await r.json():[]}return localGet()}
async function save(x){if(cfg.supabaseUrl&&cfg.supabaseAnonKey){const r=await fetch(`${cfg.supabaseUrl}/rest/v1/rsvps`,{method:"POST",headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(x)});if(!r.ok)throw Error("Could not save")}else{const a=clean();a.push(x);localStorage.setItem(key,JSON.stringify(a))}}
async function findByNickname(n,p){if(cfg.supabaseUrl&&cfg.supabaseAnonKey){const r=await fetch(`${cfg.supabaseUrl}/rest/v1/rsvps?nickname=ilike.${encodeURIComponent(n)}&edit_code=eq.${encodeURIComponent(p)}&date=gte.${iso(new Date())}&order=date.asc,created_at.desc`,{headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`}});return r.ok?await r.json():[]}return clean().filter(x=>x.nickname.toLowerCase()===n.toLowerCase()&&x.edit_code===p)}
async function update(x){if(cfg.supabaseUrl&&cfg.supabaseAnonKey){const r=await fetch(`${cfg.supabaseUrl}/rest/v1/rsvps?id=eq.${encodeURIComponent(x.id)}`,{method:"PATCH",headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(x)});if(!r.ok)throw Error("Could not update")}else{localStorage.setItem(key,JSON.stringify(clean().map(y=>y.id===x.id?x:y)))}}
async function remove(x){if(cfg.supabaseUrl&&cfg.supabaseAnonKey){const r=await fetch(`${cfg.supabaseUrl}/rest/v1/rsvps?id=eq.${encodeURIComponent(x.id)}`,{method:"DELETE",headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`}});if(!r.ok)throw Error("Could not delete")}else{localStorage.setItem(key,JSON.stringify(clean().filter(y=>y.id!==x.id)))}}
function renderTabs(){const el=document.querySelector("#day-tabs");el.innerHTML="";for(let i=0;i<7;i++){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+i);const b=document.createElement("button");b.className="day"+(iso(d)===iso(selected)?" active":"")+(i===0?" today":"");b.innerHTML=`<strong>${i===0?"TODAY":d.toLocaleDateString(undefined,{weekday:"short"}).toUpperCase()}</strong><span>${d.getDate()}</span>`;b.onclick=()=>{selected=d;render()};el.appendChild(b)}}
async function render(){renderTabs();document.querySelector("#selected-date").textContent=dateText(selected);const list=await get();document.querySelector("#player-count").textContent=list.reduce((sum,x)=>sum+(Number(x.players)||1),0);const el=document.querySelector("#players");el.innerHTML=`<h2>Players for ${selected.toLocaleDateString(undefined,{weekday:"long"})}</h2>`+(list.length?list.map(x=>`<article class="player"><div><div class="player-name">${esc(x.nickname)} <span class="badge">${esc(x.level)}</span></div><div class="player-meta">${esc(x.arrive)}–${esc(x.leave)} · ${esc(x.game)} · ${esc(x.court||"Court 1")} · ${Number(x.players)||1} player${(Number(x.players)||1)===1?"":"s"}</div>${x.description?`<div class="player-description">${esc(x.description)}</div>`:""}</div><div class="status">${esc(x.status)}</div></article>`).join(""):"<div class=\"empty\">No RSVPs yet. Be the first to let players know you’re coming!</div>")}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function toast(s){const t=document.querySelector("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),4500)}
function fillForm(x){const f=document.querySelector("#rsvp-form");for(const n of ["nickname","level","game","arrive","leave","status","court","players","description"])if(x[n]!=null&&f.elements[n])f.elements[n].value=x[n]||"";if(f.elements.edit_password)f.elements.edit_password.value=x.edit_code||""}
function openForm(){document.querySelector("#form-card").classList.remove("hidden");document.querySelector("#show-form").classList.add("hidden");document.querySelector("[name=nickname]").focus()}function closeForm(){document.querySelector("#form-card").classList.add("hidden");document.querySelector("#show-form").classList.remove("hidden");document.querySelector("#rsvp-form").reset();editing=null;document.querySelector("#form-title").textContent="Add your RSVP";document.querySelector("#delete-rsvp").classList.add("hidden")}function openManage(){document.querySelector("#manage-card").classList.remove("hidden");document.querySelector("#show-manage").classList.add("hidden");document.querySelector("[name=manage-nickname]").focus()}function closeManage(){document.querySelector("#manage-card").classList.add("hidden");document.querySelector("#show-manage").classList.remove("hidden");document.querySelector("#manage-form").reset()}
document.querySelector("[name=arrive]").innerHTML=times.map(t=>`<option>${t}</option>`).join("");document.querySelector("[name=leave]").innerHTML=times.slice(1).map(t=>`<option>${t}</option>`).join("");document.querySelector("#show-form").onclick=openForm;document.querySelector("#close-form").onclick=closeForm;document.querySelector("#show-manage").onclick=openManage;document.querySelector("#close-manage").onclick=closeManage;
document.querySelector("#rsvp-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const wasEditing=Boolean(editing);const password=f.get("edit_password").trim();const x={id:editing?editing.id:id(),date:editing?editing.date:iso(selected),nickname:f.get("nickname").trim(),level:f.get("level"),arrive:f.get("arrive"),leave:f.get("leave"),game:f.get("game"),status:f.get("status"),court:f.get("court"),players:Math.max(1,Math.min(12,Number(f.get("players"))||1)),description:f.get("description").trim(),edit_code:password};try{if(wasEditing)await update(x);else await save(x);closeForm();toast(wasEditing?"RSVP updated.":"RSVP saved.");render()}catch(err){toast(wasEditing?"Could not update right now. Please try again.":"Could not save right now. Please try again.")}};
document.querySelector("#manage-form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),n=f.get("manage-nickname").trim(),p=f.get("manage-password").trim();try{const matches=await findByNickname(n,p);if(!matches.length){toast("No RSVP found. Check your nickname and password.");return}if(matches.length>1){toast("That nickname has more than one RSVP. Use a more specific nickname.");return}editing=matches[0];selected=new Date(`${editing.date}T00:00:00`);renderTabs();fillForm(editing);document.querySelector("#form-title").textContent="Edit your RSVP";document.querySelector("#delete-rsvp").classList.remove("hidden");closeManage();openForm()}catch(err){toast("Could not find your RSVP right now. Please try again.")}};document.querySelector("#delete-rsvp").onclick=async()=>{if(!editing||!confirm("Delete this RSVP?"))return;try{await remove(editing);closeForm();toast("RSVP deleted.");render()}catch(err){toast("Could not delete right now. Please try again.")}};render();
